### PR TITLE
Update react-starter-projects.js

### PR DESCRIPTION
**Pull request by dazlious**

### CODE REVIEW

**Comment by ahfarmer** [comment]
Had some trouble with the github interface on this one so I pushed [your commit](https://github.com/ahfarmer/javascriptstuff-db/commit/a9ce1c4d32a45bade228b93623fbcd9dbb6bfdfe)  to master. Thanks!

**Comment by dazlious** [comment]
I am a bit confused: My starter package does not show up in search? Somethibg went wrong?

**Comment by ahfarmer** [comment]
Hmm yeah something went wrong. I'll look into it tonight

**Comment by ahfarmer** [comment]
@dazlious okay actually I do see it. You can find it by searching "dazlious": https://www.javascriptstuff.com/react-starter-projects/#dazlious

If you search "typescript" make sure to go to the bottom and click the 'view all' button to see it there as well.

**Comment by dazlious** [comment]
Ah, well now I see it, too. There are some issues regarding automatic tagging. Should I add the correct tags? Why is it saying I use flux?

**Pull request closed without merging**
